#!/bin/bash

# run ONLY from site root directory

#kill existing process
ps -ef |grep jekyll |grep -v grep |awk '{print "kill -9 "$2}'|sh

cd ~/sites/the-book/bin

#stop local cache
sudo ./nocache.sh 

#up the notify watches
./reupnotify.sh  

cd ~/sites/the-book/docs

bundle exec jekyll doctor
bundle exec jekyll clean

bundle exec jekyll serve --incremental &

cd -
