[crop]
cropto          = "3020x2691+298+15"  # places bottoom of stem 0.618 H

#
# Xsize x Ysize + Xoff + Yoff
#
# X/Ysize is the size of the image area desired
#
# Xoff is always relative to X=1812, which isn the vertical centerline of the image
# so, is we wanted 1200 px wide, the Xoff = 1812-(1200/2), so Xoff = 1212, and Xsize = 1200
#
# Yoff is alway related to Y=1800, which is te horozontal centerline of the image FROM THE TOP
# so, is we wanted 1600 px hight (from the starting point of the image), the Yoff = 1800-1600, Yoff = 200, and Ysize = 1600
# or "1200x1600+1212+200"...
#
# If we wanted to inclide 500 pixels BELOW the startingpoint, then we add 500 to Yoff, "1200x1600+1212+700"
#
# newwidth x newheight + 1812-(newwidth/2), 1800-(newheight +- pixels below/above 0-pt)


zoomdims         = [                                # original size - 3604 x 3604
                    ["z0","1024x1024+1298+1285"],   # bottoom of stem at center
                    ["z1","1024x1024+1279+1080"],   # middel of stem at center( (1285-1080=205=(Len/2)*6 !?
                    ["z2","1024x1024+1298+777"],    # bottom of stem at bottom center
                    ["z3","1024x1024+1290+567"],    # first split at bottom (len = 70, but pixels = 777-567=210, 3 image pixels to 1 length pixel?
                    ["z4","1200x2100+1212+200"],
                    ["z5","1200x2500+1212+300"],
                   ]
