#!/bin/bash 


if [ $# -eq 0 ]; then
    echo "$0 <directory_name> "
    echo "   ex: $0 CACTUS_99"
    echo "   (makes a cope of build.dat.sh)"
    exit 1
fi


mkdir /tmp/$1
ln -fs /tmp/$1 ./

#mkdir $1
cp build.sh build.dat.sh $1

echo "" > ${1}/description.txt
joe ${1}/build.dat.sh ${1}/description.txt
echo "joe ${1}/build.dat.sh ${1}/description.txt"

