#!/bin/bash

echo "------------------------------------------"
echo " TBD"
echo "------------------------------------------"
find -name "build.dat*" -exec grep "status=TBD" /dev/null {} \; | awk -F":" '{print "joe "$1}'|grep -v NULL|perl -p -e 's/dat.//gmi'|grep -v "\./build\.sh"
echo "------------------------------------------"
echo " ALL"
echo "------------------------------------------"
find -name "build.dat*" -exec grep "status" /dev/null {} \; | awk -F":" '{print "joe "$1}'|grep -v NULL|perl -p -e 's/dat.//gmi'|grep -v "\./build\.sh"
echo "------------------------------------------"
echo " FINISHED"
echo "------------------------------------------"
find -name "build.dat*" -exec grep "status=finished" /dev/null {} \; | awk -F":" '{print "joe "$1}'|grep -v NULL|perl -p -e 's/dat.//gmi'|grep -v "\./build\.sh"
echo "------------------------------------------"
echo " RUNNING"
echo "------------------------------------------"
find -name "build.dat*" -exec grep "status=running" /dev/null {} \; | awk -F":" '{print "joe "$1}'|grep -v NULL|perl -p -e 's/dat.//gmi'|grep -v "\./build\.sh"
echo "------------------------------------------"
echo " PENDING"
echo "------------------------------------------"
find -name "build.dat*" -exec grep "status=pending" /dev/null {} \; | awk -F":" '{print "./spawn.sh " $1";read &"}'|grep -v NULL|perl -p -e 's/dat.//gmi'|grep -v "\./build\.sh"
echo ""
find -name "build.dat*" -exec grep "status=pending" /dev/null {} \; | awk -F":" '{print $1}'|grep -v NULL|perl -p -e 's/dat.//gmi'|grep -v "\./build\.sh"
