#!/bin/python

import shutil
import os
pwd = os.getcwd()

file =f"{pwd}/build.toml"
f = open(file, 'r+')
lines = f.readlines()
f.close()

# print(lines)
print(pwd)

shutil.copy(file,f"{file}.BAK")
f = open(file, 'w')

for line in lines:
    if line.find('root') >= 0:
        line = f"root            = \"{pwd}\"\n"
    # print(f"{line}",end="")
    f.write(line)
f.close()
