#!/bin/bash 


if [ $# -eq 0 ]; then
    echo "$0 <name> <num> "
    echo "   ex: $0 CACTUS 99"
    echo "   (makes a cope of build.dat.sh)"
    exit 1
fi


R="/home/jw/books/tholonia/code/hexani"

dir="$1_$2"
mkdir $dir

cp build.toml $dir

cd $R
psn=`./Xnextpsn`
cd -

perl -pi -e "s/NEWDIR/$dir/gm" $dir/build.toml
perl -pi -e "s/NEWNAME/$1/gm" $dir/build.toml
perl -pi -e "s/NEWSERIES/$2/gm" $dir/build.toml
perl -pi -e "s/NEWPSN/$psn/gm" $dir/build.toml


echo "NAME:   [$1]"
echo "SERIES: [$2]"
echo "PSN:    [$psn]"


cd ${dir}
rm RUN XRUN ; ln -fs /home/jw/books/tholonia/code/hexani/RUN ./ && ln -fs /home/jw/books/tholonia/code/hexani/XRUN ./
ln -fs /home/jw/books/tholonia/code/hexani/UPDATE
ln -fs /home/jw/books/tholonia/code/hexani/TOMLUPDATE 
cd -

echo "" > ${dir}/predescription.txt
#joe ${dir}/build.toml ${1}/predescription.txt
echo "joe ${1}/build.toml ${1}/description.txt"

