#!/bin/bash
N=`find -name "build.toml" -exec grep PSN {} \;|grep -v NEWPSN|awk -F"=" '{print $2}'|sort -n|tail -1`

#echo "Last: $N"
let "N=N+1"
echo "$N"
echo $N > /home/jw/books/tholonia/code/hexani/nextpsn.dat
#i=$((i+1))
#((i=i+1))
#let "i=i+1"